version: "3.8"

services:
  frontend:
    build: .
    container_name: eventos-frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3100:3000"
    environment:
      NEXT_PUBLIC_API_URL: "https://api.eventos.unibague.edu.co"
    networks:
      eventos_net:
        ipv4_address: 192.168.251.11
    command: npm run start

networks:
  eventos_net:
    external: true
